Features: asynchronous and 2 options
michael-ciniawsky/posthtml-w3c pull request #4
Opened 2020-04-04 01:39 UTC by lukaszmn

Hi, I added three things to the package:

* ability to work asynchronously
* option to filter messages
* option to hide messages if there are no errors

2020-04-06 07:52 UTC, Scrum requested changes
@lukaszmn Hi, thanks for your input - this is very cool. Could you add a test for the introduced functionality?

2020-04-06 07:52 UTC, Scrum commented on index.js
> +  return async function postHTMLValidate (tree) {
No need to use `async`

2020-04-07 17:34 UTC, lukaszmn commented
Hi, what do you mean by test? There is just one example in the project. Do you want me to add another example or enhance the existing one with the new options? Or add actual unit tests?

2020-04-08 06:07 UTC, Scrum commented on index.js
> +  return async function postHTMLValidate (tree) {
Please correct this and I will merge your solution.

2020-04-08 06:07 UTC, Scrum commented
@lukaszmn Hi, oh, sorry, I didn’t notice that there aren’t any tests in them, of course it’s unfair to ask you to add them with your options when expanding.

2020-04-09 07:55 UTC, Scrum approved these changes

2020-04-09 07:55 UTC, merged

2020-04-09 08:07 UTC, Scrum commented
@lukaszmn publish v0.9.0